version: "1.0"
info:
  model: int-scaffold
packages:
- name: KusiTest2008Project
  gitServerName: kusiAZSproTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
- name: JMS2waySSL
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
- name: JMSTest
  gitServerName: SIQAPsur
  gitUrl: https://github.com/prabhakarsag
  gitUsername: prabhakarsag
  gitBranch: main
